services:
  yydb:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: yydb-dev
    entrypoint:
      - sleep
      - infinity
    init: true
    volumes:
      - ..:/YYDB
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - yydb-dev
    cap_add:
      - SYS_PTRACE

networks:
  yydb-dev:
    attachable: true
    name: yydb-dev
    ipam:
      config:
        - subnet: 192.168.24.0/26
