name: Test Library

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Dependency
      run: |
        rustup toolchain install nightly
        rustup default nightly
        rustup update

    - name: Run Tests
      run: cargo test --config 'env.LOG_LEVEL = "trace"'
      env:
        MYSQL_SOURCE_DIR: /home/runner/mysql

  typo:
    name: Spell Check with Typos
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Use custom config file
      uses: crate-ci/typos@master
      with:
        files: ./
        config: ./.github/typo.toml
